### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by reden87** [louisdh/terminal#12]
**Hi Louis!**

I have some problems with compiling the app.
I had some time to investigate what's the problem and here's what I found:

The error message for me is the following (unmodified master branch):

```
ld: warning: directory not found for option '-L/Users/gergo.nemeth/Developer/terminal/Dependencies/ios_system/Frameworks'
ld: warning: directory not found for option '-F/Users/gergo.nemeth/Developer/terminal/Dependencies/ios_system/Frameworks'
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

In Xcode I see the following:

<img width="270" alt="screen shot 2018-01-10 at 20 42 27" src="https://user-images.githubusercontent.com/869119/34791952-cc5d37a0-f646-11e7-9ee9-fc0c0c2b0473.png">

If I click the first **libcrypto.a** file in the File Inspector I see the following full file path:
`/Users/gergo.nemeth/Developer/terminal/Dependencies/libssh2-for-iOS/lib/libcrypto.a`

For the second **libcrypto.a**:
`/Users/gergo.nemeth/Developer/terminal/Dependencies/ios_system/Frameworks/libcrypto.a`

For the **libssl.a**:
`/Users/gergo.nemeth/Developer/terminal/Dependencies/libssh2-for-iOS/lib/libssl.a`

And for the **libssh2.a**:
`/Users/gergo.nemeth/Developer/terminal/Dependencies/libssh2-for-iOS/lib/libssh2.a`

The problem is that neither the **libssh2-for-iOS/lib** nor the **ios_system/Frameworks** folder can be found in the file system:

<img width="303" alt="screen shot 2018-01-10 at 20 47 00" src="https://user-images.githubusercontent.com/869119/34792189-88068ace-f647-11e7-9cc9-c40e9bbd0e99.png">

Is it possible that you did not add every file to version control?
Thanks for the answer in advance.

**Comment by louisdh** [comment]
Just committed c88a4e74606eb1dd397e7e1feba21e356c06f7f1, which should solve this issue.
Thanks for reporting!

**Comment by reden87** [comment]
Hi @louisdh,

this commit only  partially fixes the problem, 1 file reference was fixed.

**libssh2-for-iOS/lib** folder is still missing.

**Comment by haniag** [comment]
To add, I just downloaded the repo, and as soon as I hit build, I get in ViewController.swift:

`No such module 'ios_system'`

The Frameworks folder in Xcode shows both the "ios_system.framework" and "Pods_Terminal.framework" as red.

If I try to open "ios_system" Xcode project inside "/Dependencies/ios_system" to build, I get many errors related to "Apple Mach-O Linker Error Group" such as 

`"_libssh2_sftp_write", referenced from:`
`"_libssh2_sftp_read", referenced from:`

**Comment by reden87** [comment]
@haniag I believe you opened the project with the `Terminal.xcodeproj` file.

You have to open the `Terminal.xcworkspace`.

@louisdh forget my previous comment, I pulled the repository again and now it compiles just fine! Thanks for the help.

This issue can be closed now.

**Comment by louisdh** [comment]
@reden87 Good to hear!
